#!/usr/bin/env bash

set -e

basedir="$(dirname "${0}")"

source "${basedir}/includes/constants"

if [[ -z "${1}" ]]; then
    echo "Backup filename required."
    exit 1
fi

filepath="${1}"

echo "Dropping DataBase "${PGDATABASE}"..."
dropdb "${PGDATABASE}"

echo "Creating DataBase "${PGDATABASE}" with owner "${PGUSER}"..."
createdb "${PGDATABASE}" --owner "${PGUSER}"

echo "Restoring "${filepath}" to DataBase "${PGDATABASE}" with owner "${PGUSER}"..."
gunzip -c "${filepath}" | pg_restore -d "${PGDATABASE}" --no-owner --role "${PGUSER}" --verbose