# Generated by Django 5.1 on 2024-09-21 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length')
    ]

    operations = [
        migrations.CreateModel(
            name='V1OauthAccessTokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField(null=True)),
                ('access_token', models.CharField(max_length=1000, null=True)),
                ('refresh_token', models.CharField(max_length=1000, null=True)),
                ('expires', models.IntegerField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('json_roles', models.JSONField(null=True)),
                ('json_routes', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, default=None, null=True)),
                ('updated_by', models.UUIDField(blank=True, default=None, null=True)),               
            ],
            options={
                'db_table': 'v1_oauth_access_tokens',
                'indexes': [models.Index(fields=['user_id'], name='v1_oauth_ac_user_id_628eaf_idx'), models.Index(fields=['access_token'], name='v1_oauth_ac_access__f64302_idx')],
            },
        ),
        migrations.CreateModel(
            name='V1OauthClients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60, null=True)),
                ('client_secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('redirect_uri', models.CharField(max_length=300, null=True)),
                ('grant_types', models.CharField(max_length=255, null=True)),
                ('scope', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, default=None, null=True)),
                ('updated_by', models.UUIDField(blank=True, default=None, null=True)),                
            ],
            options={
                'db_table': 'v1_oauth_clients',
                'indexes': [models.Index(fields=['client_secret'], name='v1_oauth_cl_client__683754_idx')],
            },
        ),
        migrations.CreateModel(
            name='V1OauthAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.UUIDField(null=True)),
                ('grant_types', models.CharField(max_length=255, null=True)),
                ('scope', models.JSONField(null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth.v1oauthclients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, default=None, null=True)),
                ('updated_by', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'v1_oauth_authorization',
                'indexes': [models.Index(fields=['user_id'], name='v1_oauth_au_user_id_b6ff24_idx'), models.Index(fields=['code'], name='v1_oauth_au_code_f6ed84_idx')],
            },
        ),
    ]
