"""
Django settings for ccapp project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

APP_SUBDOMAINS = ['learn', 'teach', 'research']

APP_ENV_ENVIRONMENT = os.getenv('CC_ENVIRONMENT', '')
APP_ENV_PREFIX = os.getenv('CC_PREFIX', '')
APP_ENV_HOST_NAME = os.getenv('CC_HOST_NAME')
APP_ENV_HOST_APP_PORT = os.getenv('CC_HOST_APP_PORT')
APP_ENV_HOST_CLIENT_PORT = os.getenv('CC_HOST_CLIENT_PORT')
REDIS_HOST = os.getenv('CC_CACHE_HOST')
REDIS_PORT = os.getenv('CC_CACHE_PORT')

# Domains URL
APP_ENV_URL_LEARN = os.getenv('CC_URL_LEARN', '')
APP_ENV_URL_TEACH = os.getenv('CC_URL_TEACH', '')
APP_ENV_URL_RESEARCH = os.getenv('CC_URL_RESEARCH', '')

def getAppDomain() -> str:
		_main = None
		if APP_ENV_ENVIRONMENT == 'production':
				_main = f'https://{APP_ENV_HOST_NAME}'
		elif APP_ENV_ENVIRONMENT == 'development':
				_main = f'http://localhost:{APP_ENV_HOST_APP_PORT}'
		else:
				raise ValueError("APP environment type is required!")

		return _main

def getClientDomains() -> dict:
		_main = None
		_subs = []
		if APP_ENV_ENVIRONMENT == 'production':
				_main = f'https://{APP_ENV_HOST_NAME}'
				_subs.append(APP_ENV_URL_LEARN)
				_subs.append(APP_ENV_URL_TEACH)
				_subs.append(APP_ENV_URL_RESEARCH)
		elif APP_ENV_ENVIRONMENT == 'development':
				_main = f'http://localhost:{APP_ENV_HOST_CLIENT_PORT}'
				_subs.append(f'http://127.0.0.1:{APP_ENV_HOST_CLIENT_PORT}')
		else:
				raise ValueError("Client environment type is required!")
		
		_subs = [_main] + _subs
		return {
			"main": _main,
			"list": _subs
		}

def getAllowedHosts() -> list:
		_domains = ['ccapp']
		if APP_ENV_ENVIRONMENT == 'production':
				_domains.append(f'{APP_ENV_HOST_NAME}')
				_domains.append(f'{APP_ENV_URL_LEARN}'.replace("https://", ""))
				_domains.append(f'{APP_ENV_URL_TEACH}'.replace("https://", ""))
				_domains.append(f'{APP_ENV_URL_RESEARCH}'.replace("https://", ""))
		elif APP_ENV_ENVIRONMENT == 'development':
				_domains.append(f'localhost')
				_domains.append(f'127.0.0.1')
		else:
				raise ValueError("Client allowed hosts environment type is required!")
		
		return _domains


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vy42cv51y!5tz2mltpxzpvl8j304)ul9fb#jc)k*!a3v8x#6^9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = getAllowedHosts()

CORS_ALLOWED_ORIGINS = getClientDomains().get('list')

# Session manager
ESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_COOKIE_SECURE = APP_ENV_ENVIRONMENT != 'development'
SESSION_COOKIE_DOMAIN = "localhost" if APP_ENV_ENVIRONMENT == 'development' else ".cellcollective.org"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
		'rest_framework',
		'cc',
		'v1.home',
		'v1.users',
		'v1.xauth',
		'v1.oauth',
  	'corsheaders',
    'channels'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'v1.xauth.middleware.GetAuthenticatedUserAppIdMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
				"NAME": os.getenv('POSTGRES_DB'),
        "USER": os.getenv('POSTGRES_USER'),
        "PASSWORD": os.getenv('POSTGRES_PASSWORD'),
        "HOST": os.getenv('POSTGRES_HOST'),
        "PORT": os.getenv('POSTGRES_PORT'),
				"TEST": {
					"NAME": "test_ccappdb"
				}
    }
}

# CC Nodejs API secret
WEB_API_SECRET_KEY='IUr2WAaaFugM5yFn'

# Master Password token
APP_ENV_MASTER_PASSWORD_TOKEN='$2b$12$apnFwXiWBPiTO6bRB9hs0.jh.4JzyJRF7mCiDysLWY6I16MAB23OG'


# Email
EMAIL_BACKEND = os.getenv('CC_SMTP_BACKEND')
EMAIL_HOST = os.getenv('CC_SMTP_HOST')
EMAIL_USE_TLS = os.getenv('CC_SMPT_USE_TLS')
EMAIL_PORT = os.getenv('CC_SMTP_PORT')
EMAIL_HOST_USER = os.getenv('CC_SMTP_AUTH_USER')
EMAIL_HOST_PASSWORD = os.getenv('CC_SMTP_AUTH_PASSWORD')


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'EXCEPTION_HANDLER': 'cc.core_exception_handler.core_exception_handler',
		'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JSON WEB TOKEN:
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_OBTAIN_SERIALIZER': 'v1.xauth.serializers.JWTTokenObtainPairSerializer',
}

# BASE URLS:
BASE_APP_URL = f"{getAppDomain()}/v1"
BASE_FRONTEND_URL = f"{getClientDomains().get('main')}"
BASE_WEB_API_URL = f"{getClientDomains().get('main')}/web/api"


# SOCIAL: GOOGLE SOCIAL LOGIN:
GOOGLE_OAUTH2_CLIENT_ID = os.getenv('CC_GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv('CC_GOOGLE_OAUTH2_CLIENT_SECRET')
GOOGLE_OAUTH2_PROJECT_ID = os.getenv('CC_GOOGLE_OAUTH2_PROJECT_ID')
GOOGLE_OAUTH2_ORIGINS = getClientDomains().get('list')
GOOGLE_OAUTH2_REDIRECT = f"{BASE_APP_URL}/auth/google-callback"

# SOCIAL: FACEBOOK
SOCIAL_AUTH_FACEBOOK_KEY = os.getenv('CC_SOCIAL_AUTH_FACEBOOK_KEY')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('CC_SOCIAL_AUTH_FACEBOOK_SECRET')
SOCIAL_AUTH_FACEBOOK_API = "https://graph.facebook.com"
SOCIAL_AUTH_FACEBOOK_URL = "https://www.facebook.com"

# SOCIAL: LINKEDIN
SOCIAL_AUTH_LINKEDIN_KEY = os.getenv('CC_SOCIAL_AUTH_LINKEDIN_KEY')
SOCIAL_AUTH_LINKEDIN_SECRET = os.getenv('CC_SOCIAL_AUTH_LINKEDIN_SECRET')
SOCIAL_AUTH_LINKEDIN_API = "https://www.linkedin.com/oauth"

print("[SERVER]: Running at: "+getAppDomain())
print("[SERVER]: Clients: "+', '.join(getClientDomains().get('list')))
print("[SERVER]: Allowed Hosts: "+', '.join(ALLOWED_HOSTS))
