#!/usr/bin/env bash

echo "backing up db"

source /env/envs.sh

set -e

basedir="$(dirname "${0}")"

backup_dir="/backups/db"

CURDIR="$(pwd)"

echo "Removing all backups unless 5 most recent files"

cd $backup_dir

rm `ls -t | awk 'NR>5'` || echo "error removing old files"

cd $CURDIR

echo "Removing all backups unless 5 most recent files DONE"



