# Generated by Django 5.1 on 2024-11-21 08:33

from django.db import migrations
from django.contrib.auth.models import Group

def seed_members(apps, schema_editor):
  Group.objects.get_or_create(name="LABMEMBERS")


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0001_seed_groups'),
    ]

    operations = [
      migrations.RunPython(seed_members),
    ]
