# Generated by Django 5.1 on 2025-03-31 15:22

from django.db import migrations
from django.contrib.auth.models import Group

def seed_members(apps, schema_editor):
  Group.objects.get_or_create(name="TEACHERACCESSAPPROVERS")

class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0002_seed_members'),
    ]

    operations = [
      migrations.RunPython(seed_members),
    ]
