# Generated by Django 5.1 on 2024-09-18 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='V1User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField()),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, default=None, null=True)),
                ('updated_by', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'v1_user',
            },
        ),
        migrations.CreateModel(
            name='V1Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.v1user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, default=None, null=True)),
                ('updated_by', models.UUIDField(blank=True, default=None, null=True)),                
                ('institution_id', models.IntegerField(null=True)),
                ('third_party_id', models.CharField(max_length=255, null=True)),
                ('third_party_type', models.CharField(max_length=50, null=True)),
                ('avatar_uri', models.CharField(max_length=255, null=True))
            ],
            options={
                'db_table': 'v1_profile',
                'indexes': [models.Index(fields=['institution_id'], name='v1_profile_institu_ab111f_idx')],
            },
        ),
    ]
