# Generated by Django 5.1 on 2024-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='v1profile',
            name='signin_temp_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='v1profile',
            name='third_party_token',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddIndex(
            model_name='v1profile',
            index=models.Index(fields=['third_party_type'], name='v1_profile_third_p_97170b_idx'),
        ),
        migrations.AddIndex(
            model_name='v1profile',
            index=models.Index(fields=['third_party_id'], name='v1_profile_third_p_5a81b8_idx'),
        ),
    ]
