# Generated by Django 5.1 on 2024-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_v1profile_signin_temp_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v1profile',
            name='signin_temp_token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
