# Generated by Django 5.1 on 2024-11-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_v1profile_signin_temp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='v1profile',
            name='is_signin_temp_token_used',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
