# Generated by Django 5.1 on 2024-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_v1profile_is_signin_temp_token_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v1profile',
            name='avatar_uri',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
