# Generated by Django 5.1 on 2024-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_v1profile_avatar_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='v1user',
            name='app_user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
