# Generated by Django 5.1 on 2025-01-09 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_v1user_app_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='V1UserGroupRequest',
            fields=[                
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.v1user')),
                ('old_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1usergrouprequest_old_group', to='auth.group')),
                ('new_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1usergrouprequest_new_group', to='auth.group')),
                ('pending', models.BooleanField()),
								('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, default=None, null=True)),
                ('updated_by', models.UUIDField(blank=True, default=None, null=True))
            ],
            options={
                'db_table': 'v1_user_group_request',
                'indexes': [models.Index(fields=['pending'], name='v1_user_gro_pending_286574_idx')],
            },
        ),
    ]
