# Generated by Django 5.1 on 2025-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_column_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='v1usergrouprequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
