FROM docker.elastic.co/elasticsearch/elasticsearch:7.2.0

# RUN for iter in {1..10}; do yum update -y && \
#     yum install -y bash && \
#     yum clean all && exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10; done; \
#     (exit $exit_code)

# COPY ./manage /manage

# RUN chmod +x /manage/* \
#     && mv /manage/* /usr/local/bin \
#     && rmdir /manage

EXPOSE 9200